# Site settings
title: "Jungsik Blog"
description: > 
  Hello!, I'm interested in Computer Graphics and Engine.

author: Jungsik Oh
email: nemostar51@gmail.com
github_username: JungsikOh

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jungsikoh.github.io" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

